# Generated by Django 6.0.5 on 2026-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_trellixconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellixconnection',
            name='scope',
            field=models.CharField(blank=True, default='epo.device.r', max_length=500),
        ),
    ]
