# Generated by Django 6.0.5 on 2026-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_trellixconnection_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trellixconnection',
            name='auth_url',
            field=models.URLField(default='https://iam.cloud.trellix.com/oauth2/v1/token'),
        ),
    ]
