# Generated by Django 6.0.5 on 2026-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_trellixconnection_auth_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trellixconnection',
            name='auth_url',
            field=models.URLField(default='https://iam.cloud.trellix.com/iam/v1.0/token'),
        ),
    ]
