# Generated by Django 6.0.5 on 2026-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_trellixconnection_auth_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesiaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Label for this Synthesia workspace, e.g. ATLAS.', max_length=200)),
                ('base_url', models.URLField(default='https://api.synthesia.io/v2')),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'synthesia_connections',
            },
        ),
    ]
