# Generated by Django 6.0.5 on 2026-08-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_synthesiaconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesiaconnection',
            name='billing_cycle_renews_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synthesiaconnection',
            name='credit_allowance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synthesiaconnection',
            name='plan_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SynthesiaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_file', models.FileField(upload_to='synthesia_invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='integrations.synthesiaconnection')),
            ],
            options={
                'db_table': 'synthesia_invoices',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
