# Generated by Django 6.0.5 on 2026-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_synthesiaconnection_billing_cycle_renews_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesiaconnection',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='annual', max_length=10),
        ),
    ]
