# Generated by Django 6.0.5 on 2026-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_synthesiaconnection_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesiaconnection',
            name='credits_used_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synthesiaconnection',
            name='credits_used_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
