# Generated by Django 6.0.5 on 2026-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_teamviewerconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesiaconnection',
            name='credits_used_estimated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synthesiaconnection',
            name='credits_used_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
