# Generated by Django 6.0.5 on 2026-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_synthesiaconnection_credits_used_estimated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DellSupportConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(default='https://apigtwb2c.us.dell.com', help_text='Dell API gateway. US: apigtwb2c.us.dell.com, EU: apigtwb2c.eu.dell.com')),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=2000)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dell_support_connections',
            },
        ),
    ]
