# Generated by Django 6.0.5 on 2026-09-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_dellsupportconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWorkspaceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Primary or secondary domain, e.g. example.com.', max_length=253, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('admin_email', models.EmailField(help_text='Super admin the service account impersonates.', max_length=254)),
                ('service_account_json', models.TextField(blank=True)),
                ('service_account_email', models.CharField(blank=True, max_length=255)),
                ('service_account_client_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20)),
                ('last_test_message', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'google_workspace_connections',
                'ordering': ['domain'],
            },
        ),
    ]
