# Generated by Django 6.0.5 on 2026-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_googleworkspaceconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trellixconnection',
            name='scope',
            field=models.CharField(blank=True, default='epo.device.r epo.evt.r', max_length=500),
        ),
    ]
