# Generated by Django 6.0.5 on 2026-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sops',
            },
        ),
        migrations.CreateModel(
            name='SOPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SOP Category',
                'db_table': 'sop_categories',
            },
        ),
        migrations.CreateModel(
            name='SOPChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sop_checklist_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SOPExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(blank=True, max_length=100)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sop_executions',
            },
        ),
        migrations.CreateModel(
            name='SOPStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('action', 'Action'), ('checklist', 'Checklist'), ('condition', 'Condition'), ('approval', 'Approval')], default='action', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('responsible_role', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'sop_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='SOPStepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('checklist_data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'sop_step_completions',
            },
        ),
    ]
