# Generated by Django 6.0.5 on 2026-05-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sopcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='sop.sopcategory'),
        ),
        migrations.AddField(
            model_name='sopexecution',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='sop.sop'),
        ),
        migrations.AddField(
            model_name='sopexecution',
            name='started_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sopstep',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sop.sop'),
        ),
        migrations.AddField(
            model_name='sopchecklistitem',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='sop.sopstep'),
        ),
        migrations.AddField(
            model_name='sopstepcompletion',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sopstepcompletion',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='sop.sopexecution'),
        ),
        migrations.AddField(
            model_name='sopstepcompletion',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sop.sopstep'),
        ),
        migrations.AlterUniqueTogether(
            name='sopstepcompletion',
            unique_together={('execution', 'step')},
        ),
    ]
