# Generated by Django 6.0.5 on 2026-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0003_alter_sopstep_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sopstep',
            name='step_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated'), ('checklist', 'Checklist'), ('approval', 'Approval')], default='action', max_length=20),
        ),
    ]
