# Generated by Django 6.0.5 on 2026-06-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_installed_app_report_import'),
        ('organisations', '0003_add_organisation_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='installedapplication',
            new_name='installed_a_normali_cadd36_idx',
            old_name='installed_a_normali_58ad48_idx',
        ),
        migrations.AddField(
            model_name='asset',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_licenses', to='organisations.organisation'),
        ),
    ]
