# Generated by Django 6.0.5 on 2026-07-10 11:34

from django.db import migrations, models


def copy_organisation_to_organisations(apps, schema_editor):
    SoftwareLicense = apps.get_model('inventory', 'SoftwareLicense')
    for license_obj in SoftwareLicense.objects.exclude(organisation__isnull=True):
        license_obj.organisations.add(license_obj.organisation_id)


def copy_organisations_to_organisation(apps, schema_editor):
    SoftwareLicense = apps.get_model('inventory', 'SoftwareLicense')
    for license_obj in SoftwareLicense.objects.all():
        first_org_id = license_obj.organisations.values_list('id', flat=True).first()
        if first_org_id:
            license_obj.organisation_id = first_org_id
            license_obj.save(update_fields=['organisation'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_assettypeattributerequirement'),
        ('organisations', '0003_add_organisation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarelicense',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='software_licenses', to='organisations.organisation'),
        ),
        migrations.RunPython(copy_organisation_to_organisations, copy_organisations_to_organisation),
        migrations.RemoveField(
            model_name='softwarelicense',
            name='organisation',
        ),
    ]
