# Generated by Django 6.0.5 on 2026-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_softwarelicense_organisations_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarelicense',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
