# Generated by Django 6.0.5 on 2026-09-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_softwarelicense_unlimited'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSupportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, choices=[('dell', 'Dell'), ('lenovo', 'Lenovo')], max_length=20)),
                ('service_tag', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('warranty', models.JSONField(blank=True, default=dict)),
                ('product_specifications', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('unsupported', 'Unsupported')], default='pending', max_length=20)),
                ('fetch_error', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_info', to='inventory.asset')),
            ],
            options={
                'db_table': 'asset_support_info',
            },
        ),
    ]
