# Generated by Django 6.0.5 on 2026-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewJoinerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('complete_address', models.TextField()),
                ('designation', models.CharField(max_length=200)),
                ('core_process', models.CharField(max_length=200)),
                ('alias_name', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.DateField()),
                ('line_manager', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
