# Generated by Django 6.0.5 on 2026-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newjoinerrequest',
            name='complete_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newjoinerrequest',
            name='core_process',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newjoinerrequest',
            name='line_manager',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
