# Generated by Django 6.0.5 on 2026-05-08 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0001_initial'),
        ('employees', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetallocation',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='assetallocation',
            name='recovered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_recoveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseallocation',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenseallocation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_allocations', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='licenseallocation',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.softwarelicense'),
        ),
        migrations.AddField(
            model_name='licenseallocation',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_revocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
