# Generated by Django 6.0.5 on 2026-09-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_initial'),
        ('employees', '0008_employee_client_email'),
        ('inventory', '0008_softwarelicense_unlimited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseallocation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_allocations', to='inventory.asset'),
        ),
        migrations.AlterField(
            model_name='licenseallocation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_allocations', to='employees.employee'),
        ),
        migrations.AddConstraint(
            model_name='licenseallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', True), ('employee__isnull', False)), models.Q(('asset__isnull', False), ('employee__isnull', True)), _connector='OR'), name='license_allocation_employee_xor_asset'),
        ),
    ]
