# Generated by Django 6.0.5 on 2026-05-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('alias_name', models.CharField(blank=True, max_length=100)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('core_process', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['full_name'],
            },
        ),
    ]
