# Generated by Django 6.0.5 on 2026-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_non_base_employees_from_base_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_separation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
