# Generated by Django 6.0.5 on 2026-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_date_of_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
